# Generated by Django 5.0 on 2023-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=40)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
