# Generated by Django 5.0 on 2023-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_description_alter_item_price_item2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
