# Generated by Django 5.0 on 2023-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birth_date', models.DateField(null=True)),
                ('aliace', models.CharField(max_length=50)),
            ],
        ),
    ]
